project:
  type: website

website:
  title: "ISSS608"
  navbar:
    left:
    - text: "Hands-on Exercises"
      menu:
      - text: "Hands-on Exercise 01"
        href: "HandsOnEx/HandsOnEx01/HandsOnEx01.qmd"
    - text: "In-class Exercises"
      menu:
      - text: "In-class Exercise 03"
        href: "InClassEx/InClassEx03/InClassEx03.qmd"
      - text: "In-class Exercise 04"
        href: "InClassEx/InClassEx04/InClassEx04.qmd"
      - text: "In-class Exercise 05"
        href: "InClassEx/InClassEx05/InClassEx05.qmd"
      - text: "In-class Exercise 07"
        href: "InClassEx/InClassEx07/InClassEx07.qmd"
      - text: "In-class Exercise 08"
        href: "InClassEx/InClassEx08/InClassEx08.qmd"
    - text: "Take Home Exercises"
      menu:
      - text: "Take Home Exercise 01"
        href: "TakeHomeEx/TakeHomeEx01/TakeHomeEx01.qmd"
      - text: "Take Home Exercise 02"
        href: "TakeHomeEx/TakeHomeEx02/TakeHomeEx02.qmd"
      - text: "Take Home Exercise 03"
        href: "TakeHomeEx/TakeHomeEx03/TakeHomeEx03.qmd"
      - text: "Take Home Exercise 04"
        href: "TakeHomeEx/TakeHomeEx04/TakeHomeEx04.qmd"
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: slate
    css: styles.css
    toc: true

editor: visual

